[package]
name = "rust-malware"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-core = "0.61.2"

[dependencies.windows]
version = "0.61.3"
features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
